### PR TITLE
added mayhem support

### PR DESCRIPTION
**Pull request by matl4c**

### CODE REVIEW

**Comment by noahShinabarger** [comment]
@matl4c the Heroes program is not currently accepting submissions--stay posted for Phase III, starting later this Spring, and resubmit then--thank you!

**Comment by noahShinabarger** [comment]
My bad--I failed to see you submitted this in 2022--reopening and will evaluate for payment later today.

**Comment by noahShinabarger** [comment]
@matl4c unfortunately this is running really slowly (~1 test per second) and we require submissions to have at least 10 tests per second before they're eligible to be merged. If you can speed it up in the next few days, tag me and we'll get this merged. Unfortunately it seems like the `guessit` function just takes a while. You could try fuzzing specific subroutines, instead of the main `guessit` function--that would probably be faster.

**Comment by xansec** [comment]
Stale.

**Pull request closed without merging**
